version: "3.9"
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile

    networks:
      - shop-sport-network
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  db-data:
networks:
  shop-sport-network:
      name: shop-sport-network
